# DS 310 Fall 2021 : Lab 1 
## Sept. 02, 2021


Outcomes from this lab

1. Importing modules
2. Some basic calculations
3. Functions
4. Key libraries (NumPy, Pandas, Matplotlib)
5. Exercises (Submission Deadline **Sept. 5, 2021 on CANVAS**) 

## Example : Lab 1 exercise will be due 9/5 at 11:59 PM.
---



In [1]:
#Use shortforms to make your job easier!

import numpy as np                #Numpy helps with manipulation of large, multi-dimensional arrays and matrices
import pandas as pd               #Data manipulation & Analysis
import scipy                      #Additional functionality over np
import matplotlib.pyplot as plt   #Plots

In [2]:
#
1+2


3

In [3]:
a = 1+2
#Will we get any output? 

In [4]:
#Basic Function 
def sum_product(a,b):
    sum_output = a+b
    prod_output = a*b
    return sum_output,prod_output

In [5]:
sum_product(5,10)

(15, 50)


### Numpy

---

* Numpy array - from list, special functions
* Array operations
* 2-D arrays
* Indexing and slicing
* Conditional subsetting
* Array-array operations

### Pandas

---

* Pandas series
* DataFrame - creation, read from files
* Quick checking DataFrame
* Descriptive stats on DataFrame
* Indexing, slicing, conditional subsetting
* Operations on specific rows/columns

## Numpy array from a Python list
Numpy arrays behave like **true numerical vectors**, not ordinary lists. That's why they are used for all mathematical operations, machine learning algorithms, and as basis of Pandas DataFrame for data analytics.

In [6]:
import numpy as np
list1=[1,2,3]
array1 = np.array(list1)

In [7]:
type(list1)

list

In [8]:
type(array1)

numpy.ndarray

In [9]:
list2=[4,5,6]
array2 = np.array(list2)

In [10]:
print(f"Adding two lists {list1} and {list2} together: {list1+list2}")

Adding two lists [1, 2, 3] and [4, 5, 6] together: [1, 2, 3, 4, 5, 6]


In [11]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")

Adding two numpy arrays [1 2 3] and [4 5 6] together: [5 7 9]


## Mathematical operations with/on Numpy arrays

In [12]:
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)

array2 multiplied by array1:  [ 4 10 18]
array2 divided by array1:  [4.  2.5 2. ]
array2 raised to the power of array1:  [  4  25 216]


In [13]:
# sine function
print("Sine: ",np.sin(array1))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
# Exponential
print("Exponential: ",np.exp(array1))

Sine:  [0.84147098 0.90929743 0.14112001]
Natural logarithm:  [0.         0.69314718 1.09861229]
Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-2 logarithm:  [0.        1.        1.5849625]
Exponential:  [ 2.71828183  7.3890561  20.08553692]


## How to generate arrays easily?
* `np.zeros`
* `np.ones`
* `np.arange`

In [14]:
print("A series of zeroes:",np.zeros(5))
print("A series of ones:",np.ones(7))
print("A series of numbers:",np.arange(5,7))

A series of zeroes: [0. 0. 0. 0. 0.]
A series of ones: [1. 1. 1. 1. 1. 1. 1.]
A series of numbers: [5 6]


## Multi-dimensional arrays

In [15]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("The matrix is",mat)

Type/Class of this object: <class 'numpy.ndarray'>
The matrix is [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Dimension, shape, size, and data type of the 2D array

In [16]:
print("Dimension of this matrix: ",mat.ndim,sep='') 
print("Size of this matrix: ", mat.size,sep='') 
print("Shape of this matrix: ", mat.shape,sep='')
print("Data type of this matrix: ", mat.dtype,sep='')

Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


## Zeros, Ones, Random, and Identity Matrices and Vectors

In [17]:
print("Vector of zeros: ",np.zeros(5))
print("Matrix of zeros: ",np.zeros((2,3)))
print("Vector of ones: ",np.ones(4))
print("Matrix of ones: ",np.ones((2,4)))
print("Matrix of 7’s: ",7*np.ones((3,3)))
print("Identity matrix of dimension 2:",np.eye(2))

Vector of zeros:  [0. 0. 0. 0. 0.]
Matrix of zeros:  [[0. 0. 0.]
 [0. 0. 0.]]
Vector of ones:  [1. 1. 1. 1.]
Matrix of ones:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matrix of 7’s:  [[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
Identity matrix of dimension 2: [[1. 0.]
 [0. 1.]]


## Indexing and slicing

In [18]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 2rd to 4th index are:", arr[2:5])
print("Elements up to 4th index are:", arr[:4])

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 2rd to 4th index are: [2 3 4]
Elements up to 4th index are: [0 1 2 3]


## Pandas series

In [19]:
import pandas as pd

In [20]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


In [21]:
s1=pd.Series(data=my_data)
print(s1)

0    10
1    20
2    30
dtype: int64


In [22]:
s2=pd.Series(data=my_data, index=labels)
print(s2)

a    10
b    20
c    30
dtype: int64


In [23]:
s3=pd.Series(arr, labels)
print(s3)

a    10
b    20
c    30
dtype: int64


In [24]:
s4=pd.Series(d)
print(s4)

a    10
b    20
c    30
dtype: int64


## Pandas DataFrame

In [25]:
matrix_data = np.random.randint(1,20,size=20).reshape(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
print(df)


The data frame looks like
---------------------------------------------
    W   X   Y   Z
A   5  11  19   8
B   7   8  13   5
C  19   5  15  12
D  15   5   7  14
E  12  18  17  10


In [26]:
d={'a':[10,20],'b':[30,40],'c':[50,60]}
df2=pd.DataFrame(data=d,index=['X','Y'])
print(df2)

    a   b   c
X  10  30  50
Y  20  40  60


## DataFrame can be created reading directly from a CSV or an Excel file

In [27]:
df3 = pd.read_csv("https://raw.githubusercontent.com/suhasbn/DS310/master/us_airport_traffic_2011.csv")


In [28]:
df3.head()

iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

## Quick checking DataFrames
* `.head()`
* `.tail()`
* `.sample()`
* `.info()`
* `.describe()`

In [29]:
df3.head(3)

iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   

         lat       long    cnt  
0  41.979595 -87.904464  25129  
1  33.640444 -84.426944  21925  
2  32.895951 -97.037200  20662

In [30]:
df3.tail(7)

iata                               airport           city state country  \
214  SPS  Sheppard AFB/Wichita Falls Municipal  Wichita Falls    TX     USA   
215  FAY                Fayetteville Municipal   Fayetteville    NC     USA   
216  EAU              Chippewa Valley Regional     Eau Claire    WI     USA   
217  DBQ                     Dubuque Municipal        Dubuque    IA     USA   
218  RST               Rochester International      Rochester    MN     USA   
219  UTM              Tunica Municipal Airport         Tunica    MS     USA   
220  BIL                   Billings Logan Intl       Billings    MT     USA   

           lat        long  cnt  
214  33.988796  -98.491893   50  
215  34.991472  -78.880000   50  
216  44.865257  -91.485072   48  
217  42.402959  -90.709167   48  
218  43.908826  -92.497987   37  
219  34.681499  -90.348816   32  
220  45.807662 -108.542861   23

In [31]:
df3.sample(5)

iata                             airport           city state country  \
109  CID                       Eastern Iowa    Cedar Rapids    IA     USA   
27   BWI  Baltimore-Washington International      Baltimore    MD     USA   
6    SFO         San Francisco International  San Francisco    CA     USA   
67   RIC              Richmond International       Richmond    VA     USA   
55   ONT               Ontario International        Ontario    CA     USA   

           lat        long    cnt  
109  41.884588  -91.710872    516  
27   39.175402  -76.668198   4749  
6    37.619002 -122.374843  12016  
67   37.505167  -77.319667   1199  
55   34.056000 -117.601194   1622

In [32]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   iata     221 non-null    object 
 1   airport  221 non-null    object 
 2   city     220 non-null    object 
 3   state    220 non-null    object 
 4   country  221 non-null    object 
 5   lat      221 non-null    float64
 6   long     221 non-null    float64
 7   cnt      221 non-null    int64  
dtypes: float64(2), int64(1), object(5)
memory usage: 13.9+ KB


In [33]:
df3.describe()

lat        long           cnt
count  221.000000  221.000000    221.000000
mean    37.722000  -94.650006   1998.764706
std      5.460631   15.067309   3751.580879
min     25.793250 -124.246028     23.000000
25%     33.663639 -106.917695    168.000000
50%     38.036972  -90.709167    479.000000
75%     41.884588  -82.407421   1622.000000
max     48.792750  -70.308750  25129.000000

## Basic descriptive statistics on a DataFrame
* `mean()`
* `std()`
* `var()`
* `min()` and `max()`

In [34]:
df3.mean()

lat       37.722000
long     -94.650006
cnt     1998.764706
dtype: float64

In [35]:
df3.std()

lat        5.460631
long      15.067309
cnt     3751.580879
dtype: float64

In [36]:
df3.min()

iata                    ABE
airport    Abilene Regional
country                 USA
lat                25.79325
long            -124.246028
cnt                      23
dtype: object

## Indexing, slicing columns and rows of a DataFrame

In [37]:
print("\nThe 'iata' column\n",'-'*25, sep='')
print(df3['iata'])
print("\nType of the column: ", type(df3['iata']), sep='')
print("\nThe 'iata' and 'cnt' columns indexed by passing a list\n",'-'*55, sep='')
print(df3[['iata','cnt']])
print("\nType of the pair of columns: ", type(df3[['iata','cnt']]), sep='')


The 'iata' column
-------------------------
0      ORD
1      ATL
2      DFW
3      PHX
4      DEN
      ... 
216    EAU
217    DBQ
218    RST
219    UTM
220    BIL
Name: iata, Length: 221, dtype: object

Type of the column: <class 'pandas.core.series.Series'>

The 'iata' and 'cnt' columns indexed by passing a list
-------------------------------------------------------
    iata    cnt
0    ORD  25129
1    ATL  21925
2    DFW  20662
3    PHX  17290
4    DEN  13781
..   ...    ...
216  EAU     48
217  DBQ     48
218  RST     37
219  UTM     32
220  BIL     23

[221 rows x 2 columns]

Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>


In [38]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.loc['C'])
print("\nMultiple rows\n")
print(df.loc[['B','C']])
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W    19
X     5
Y    15
Z    12
Name: C, dtype: int64

Multiple rows

    W  X   Y   Z
B   7  8  13   5
C  19  5  15  12

Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W    19
X     5
Y    15
Z    12
Name: C, dtype: int64

Multiple rows

    W  X   Y   Z
B   7  8  13   5
C  19  5  15  12


## True/False Conditional subsetting

In [39]:
df3['lat']>35

0       True
1      False
2      False
3      False
4       True
       ...  
216     True
217     True
218     True
219    False
220     True
Name: lat, Length: 221, dtype: bool

###List all the cities (and their corresponding parameters) that have a lattitude value of more than 35 degrees.

In [40]:
df3[df3['lat']>35]

iata                          airport            city state country  \
0    ORD     Chicago O'Hare International         Chicago    IL     USA   
4    DEN                      Denver Intl          Denver    CO     USA   
6    SFO      San Francisco International   San Francisco    CA     USA   
9    CLT  Charlotte/Douglas International       Charlotte    NC     USA   
10   SLC              Salt Lake City Intl  Salt Lake City    UT     USA   
..   ...                              ...             ...   ...     ...   
212  BKG                  Branson Airport       Hollister    MO     USA   
216  EAU         Chippewa Valley Regional      Eau Claire    WI     USA   
217  DBQ                Dubuque Municipal         Dubuque    IA     USA   
218  RST          Rochester International       Rochester    MN     USA   
220  BIL              Billings Logan Intl        Billings    MT     USA   

           lat        long    cnt  
0    41.979595  -87.904464  25129  
4    39.858408 -104.667002  13781  
6    37.619002 -122.374843  12016  
9    35.214011  -80.943126  10490  
10   40.788388 -111.977773   9898  
..         ...         ...    ...  
212  36.385913  -92.548828     56  
216  44.865257  -91.485072     48  
217  42.402959  -90.709167     48  
218  43.908826  -92.497987     37  
220  45.807662 -108.542861     23  

[147 rows x 8 columns]

**Lattitude more than 35 degrees and a Longitude less than -90 degrees?**

In [41]:
df3[(df3['lat']>35) & (df3['long']<-90)]

iata                      airport            city state country  \
4    DEN                  Denver Intl          Denver    CO     USA   
6    SFO  San Francisco International   San Francisco    CA     USA   
10   SLC          Salt Lake City Intl  Salt Lake City    UT     USA   
13   LAS       McCarran International       Las Vegas    NV     USA   
15   MSP     Minneapolis-St Paul Intl     Minneapolis    MN     USA   
..   ...                          ...             ...   ...     ...   
212  BKG              Branson Airport       Hollister    MO     USA   
216  EAU     Chippewa Valley Regional      Eau Claire    WI     USA   
217  DBQ            Dubuque Municipal         Dubuque    IA     USA   
218  RST      Rochester International       Rochester    MN     USA   
220  BIL          Billings Logan Intl        Billings    MT     USA   

           lat        long    cnt  
4    39.858408 -104.667002  13781  
6    37.619002 -122.374843  12016  
10   40.788388 -111.977773   9898  
13   36.080361 -115.152333   8523  
15   44.880547  -93.216922   7690  
..         ...         ...    ...  
212  36.385913  -92.548828     56  
216  44.865257  -91.485072     48  
217  42.402959  -90.709167     48  
218  43.908826  -92.497987     37  
220  45.807662 -108.542861     23  

[78 rows x 8 columns]

## Operations on specific columns/rows

In [42]:
df3.head()

iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

#### What is the standard deviation of Lattitude and Longitude?

In [43]:
df3[['lat','long']].std()

lat      5.460631
long    15.067309
dtype: float64

## Create a new column as a function of mathematical operations on existing columns

In [44]:
df3['SomeRandomNewParameter']=df3['lat']*0.453592/(df3['long']/100)**2
df3

iata                            airport               city state country  \
0    ORD       Chicago O'Hare International            Chicago    IL     USA   
1    ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2    DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3    PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4    DEN                        Denver Intl             Denver    CO     USA   
..   ...                                ...                ...   ...     ...   
216  EAU           Chippewa Valley Regional         Eau Claire    WI     USA   
217  DBQ                  Dubuque Municipal            Dubuque    IA     USA   
218  RST            Rochester International          Rochester    MN     USA   
219  UTM           Tunica Municipal Airport             Tunica    MS     USA   
220  BIL                Billings Logan Intl           Billings    MT     USA   

           lat        long    cnt  SomeRandomNewParameter  
0    41.979595  -87.904464  25129               24.642330  
1    33.640444  -84.426944  21925               21.407451  
2    32.895951  -97.037200  20662               15.846426  
3    33.434167 -112.008056  17290               12.088081  
4    39.858408 -104.667002  13781               16.503109  
..         ...         ...    ...                     ...  
216  44.865257  -91.485072     48               24.315045  
217  42.402959  -90.709167     48               23.375408  
218  43.908826  -92.497987     37               23.278374  
219  34.681499  -90.348816     32               19.271624  
220  45.807662 -108.542861     23               17.636036  

[221 rows x 9 columns]

In [45]:
df3.sort_values(by='SomeRandomNewParameter')

iata                                airport             city state  \
20   SAN     San Diego International-Lindbergh         San Diego    CA   
83   SBA                Santa Barbara Municipal    Santa Barbara    CA   
156  SMX  Santa Maria Pub/Capt G Allan Hancock       Santa Maria    CA   
7    LAX              Los Angeles International      Los Angeles    CA   
182  SBP          San Luis Obispo Co-McChesney   San Luis Obispo    CA   
..   ...                                    ...              ...   ...   
50   PVD                 Theodore F Green State       Providence    RI   
199  BTV               Burlington International       Burlington    VT   
25   BOS                   Gen Edw L Logan Intl           Boston    MA   
76   MHT                             Manchester       Manchester    NH   
90   PWM         Portland International Jetport         Portland    ME   

    country        lat        long    cnt  SomeRandomNewParameter  
20      USA  32.733556 -117.189657   6233               10.811352  
83      USA  34.426212 -119.840373    800               10.872973  
156     USA  34.899248 -120.457583    216               10.909709  
7       USA  33.942536 -118.408074  11797               10.981130  
182     USA  35.237058 -120.642393    112               10.981588  
..      ...        ...         ...    ...                     ...  
50      USA  41.723999  -71.428221   2044               37.094681  
199     USA  44.473004  -73.150312     91               37.698969  
25      USA  42.364348  -71.005179   5627               38.114116  
76      USA  42.934516  -71.437056    953               38.161450  
90      USA  43.646167  -70.308750    686               40.049098  

[221 rows x 9 columns]

#Exercise : Take a screenshot of all the results and upload them onto CANVAS (preferably as a single PDF file)
1. Calculate the `var()` on dataframe3
2. Calculate `max()` on dataframe3
3. What is the `range` of lattitudes on dataframe3? 
4. List the `top 5 percentile` in terms of cnt parameter.
